# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np 

In [2]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

# Create a 3-dimensional Numpy array using np.array()
arr3 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
shape = arr1.shape
dimensions = arr1.ndim
data_type = arr1.dtype
size = arr1.size
array_type = type(arr1)

print("Shape of the array:", shape)
print("Number of dimensions:", dimensions)
print("Data type of the array elements:", data_type)
print("Size of the array", size)
print("Type of the array:", array_type)


Shape of the array: (8,)
Number of dimensions: 1
Data type of the array elements: int32
Size of the array 8
Type of the array: <class 'numpy.ndarray'>


In [51]:
# Attributes of 2-dimensional array

shape = arr2.shape
dimensions = arr2.ndim
data_type = arr2.dtype
size = arr2.size
array_type = type(arr2)

print("Shape of the array:", shape)
print("Number of dimensions:", dimensions)
print("Data type of the array elements:", data_type)
print("Size of the array", size)
print("Type of the array:", array_type)


Shape of the array: (2, 4)
Number of dimensions: 2
Data type of the array elements: int32
Size of the array 8
Type of the array: <class 'numpy.ndarray'>


In [52]:
# Attributes of 3-dimensional array

shape = arr3.shape
dimensions = arr3.ndim
data_type = arr3.dtype
size = arr3.size
array_type = type(arr3)

print("Shape of the array:", shape)
print("Number of dimensions:", dimensions)
print("Data type of the array elements:", data_type)
print("Size of the array", size)
print("Type of the array:", array_type)

Shape of the array: (2, 2, 2)
Number of dimensions: 3
Data type of the array elements: int32
Size of the array 8
Type of the array: <class 'numpy.ndarray'>


In [54]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created

import pandas as pd
df = pd.DataFrame(arr1, columns=['arr1'])

print(df)

   arr1
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8


In [56]:
# Create an array of shape (10, 2) with only ones
array_ones = np.ones((10, 2))
array_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [57]:
# Create an array of shape (7, 2, 3) of only zeros
array_zeros = np.zeros((7, 2,3))
array_zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [58]:
# Create an array within a range of 0 and 100 with step 3
array_range_with_step = np.arange(0, 100, 3)
array_range_with_step

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [59]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
array_random = np.random.randint(0, 11, size=(7, 2))
array_random

array([[9, 0],
       [8, 2],
       [1, 1],
       [1, 3],
       [4, 2],
       [4, 4],
       [4, 7]])

In [60]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
array_random_float = np.random.rand(3, 5)
array_random_float

array([[0.61996519, 0.58150017, 0.40831757, 0.38576894, 0.44685122],
       [0.56156549, 0.14253621, 0.5401439 , 0.74478641, 0.05697014],
       [0.939077  , 0.2560283 , 0.61919202, 0.31133223, 0.00974544]])

In [63]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array = np.random.randint(0, 11, size=(4, 6))
random_array

array([[ 6,  3, 10,  7,  4,  6],
       [ 9,  2,  6, 10, 10,  7],
       [ 4,  3,  7,  7,  2,  5],
       [ 4,  1,  7,  5,  1,  4]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

------------------------------------------------------------------------------------------------------------------------------
Answer:

setting the random seed to a specific value ensures that the random numbers generated are reproducible. so I will get the same set of random numbers every time I run the code.

In [65]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array = np.random.randint(1, 11, size=(3, 7))
print(random_array)

# Find the unique numbers in the array you just created
unique_numbers = np.unique(random_array)
unique_numbers

[[10  9 10  5  2  4  7]
 [ 8  3  1  4  2  8  4]
 [ 2  6  6 10  4  6  2]]


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [66]:
# Find the 0'th index of the latest array you created
random_array[0, 0]

10

In [67]:
# Get the first 2 rows of latest array you created
random_array[:2, :]

array([[10,  9, 10,  5,  2,  4,  7],
       [ 8,  3,  1,  4,  2,  8,  4]])

In [68]:
# Get the first 2 values of the first 2 rows of the latest array
random_array[:2, :2]

array([[10,  9],
       [ 8,  3]])

In [72]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables

random_arr = np.random.randint(0, 11, size=(3, 5))
ones_arr = np.ones((3, 5))

print(random_arr)
print(" ")
print(ones_arr)

[[ 2  7  5 10  2]
 [ 0  2  4  2  0]
 [ 4  9  6  6 10]]
 
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [74]:
# Add the two arrays together
add = random_arr + ones_arr

add

array([[ 3.,  8.,  6., 11.,  3.],
       [ 1.,  3.,  5.,  3.,  1.],
       [ 5., 10.,  7.,  7., 11.]])

In [75]:
# Create another array of ones of shape (5, 3)
ones_arr2 = np.ones((5, 3))
ones_arr2

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [79]:
# Try add the array of ones and the other most recent array together
result= add + ones_arr2.T
result

array([[ 4.,  9.,  7., 12.,  4.],
       [ 2.,  4.,  6.,  4.,  2.],
       [ 6., 11.,  8.,  8., 12.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

------------------------------------------------------------------------------------------------------------------------------
Answer:
The error occurs because the two arrays have different shapes. 

To add two arrays they should either be the same shape or one of them should be casted to the shape of the other. so here we can transpose it.




In [82]:
# Create another array of ones of shape (3, 5)
ones_arr3 = np.ones((3,5))

ones_arr3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [83]:
# Subtract the new array of ones from the other most recent array
subtract = result - ones_arr3

subtract

array([[ 3.,  8.,  6., 11.,  3.],
       [ 1.,  3.,  5.,  3.,  1.],
       [ 5., 10.,  7.,  7., 11.]])

In [84]:
# Multiply the ones array with the latest array
multiply = ones_arr3 * subtract

multiply

array([[ 3.,  8.,  6., 11.,  3.],
       [ 1.,  3.,  5.,  3.,  1.],
       [ 5., 10.,  7.,  7., 11.]])

In [86]:
# Take the latest array to the power of 2 using '**'
power = multiply ** 2

power

array([[  9.,  64.,  36., 121.,   9.],
       [  1.,   9.,  25.,   9.,   1.],
       [ 25., 100.,  49.,  49., 121.]])

In [88]:
# Do the same thing with np.square()
power2= np.square(multiply)
power2

array([[  9.,  64.,  36., 121.,   9.],
       [  1.,   9.,  25.,   9.,   1.],
       [ 25., 100.,  49.,  49., 121.]])

In [89]:
# Find the mean of the latest array using np.mean()
mean = np.mean(power2)

mean

41.86666666666667

In [91]:
# Find the maximum of the latest array using np.max()
max= np.max(power2)

max

121.0

In [92]:
# Find the minimum of the latest array using np.min()

min= np.min(power2)

min

1.0

In [93]:
# Find the standard deviation of the latest array
std= np.std(power2)

std

40.62817850813507

In [94]:
# Find the variance of the latest array
variance = np.var(power2)

variance

1650.6488888888887

In [96]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = np.reshape(power2, (3, 5, 1))

reshaped_array

array([[[  9.],
        [ 64.],
        [ 36.],
        [121.],
        [  9.]],

       [[  1.],
        [  9.],
        [ 25.],
        [  9.],
        [  1.]],

       [[ 25.],
        [100.],
        [ 49.],
        [ 49.],
        [121.]]])

In [98]:
# Transpose the latest array
trans = reshaped_array.T

trans

array([[[  9.,   1.,  25.],
        [ 64.,   9., 100.],
        [ 36.,  25.,  49.],
        [121.,   9.,  49.],
        [  9.,   1., 121.]]])

What does the transpose do?

-------------------------------------------------------------------------------------------------------------------------------
the transpose operation flips the matrix over its diagonal, swapping its rows and columns. In other words, the rows become columns, and the columns become rows.

In [102]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)

random_array_1 = np.random.randint(0, 11, size=(3, 3))
random_array_2 = np.random.randint(0, 11, size=(3, 2))


In [101]:
# Perform a dot product on the two newest arrays you created

dot_product = np.dot(random_array_1, random_array_2)
dot_product

array([[192, 165],
       [ 72,  30],
       [ 72,  67]])

In [103]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array_3 = np.random.randint(0, 11, size=(4, 3))
random_array_4 = np.random.randint(0, 11, size=(4, 3))


In [106]:
# Perform a dot product on the two newest arrays you created
dot_product = np.dot(random_array_3, random_array_4)
dot_product

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

-------------------------------------------------------------------------------------------------------------------------------

Answer:
No beacuse dot product operation requires the number of columns in the first matrix to be equal to the number of rows in the second matrix., I can transpose one of them.


In [107]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both

dot_product = np.dot(random_array_3, random_array_4.T)
dot_product

array([[ 92, 196, 160,  72],
       [ 34, 111,  91,  18],
       [ 73, 127, 103,  63],
       [ 52, 170, 146,  36]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [108]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
array_1 = np.random.randint(0, 11, size=(4, 3))
array_2 = np.random.randint(0, 11, size=(4, 3))

In [109]:
# Compare the two arrays with '>'
comparison_result = array_1 > array_2
comparison_result

array([[ True,  True, False],
       [False, False,  True],
       [False,  True, False],
       [ True, False, False]])

What happens when you compare the arrays with `>`?

------------------------------------------------------------------------------------------------------------------------------

Answer:

The > operator is used to compare the elements of the two arrays element-wise. The resulting comparison_result will contain True where the corresponding elements in array_1 are greater than the elements in array_2, and False otherwise.

In [110]:
# Compare the two arrays with '>='
comparison_result2 = array_1 >= array_2
comparison_result2

array([[ True,  True, False],
       [False,  True,  True],
       [False,  True, False],
       [ True, False, False]])

In [111]:
# Find which elements of the first array are greater than 7
elements_greater_than_7 = array_1 > 7
elements_greater_than_7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [ True, False, False]])

In [117]:
# Which parts of each array are equal? (try using '==')
equal_elements = (array_1 == array_2)
equal_elements

array([[False, False, False],
       [False,  True, False],
       [False, False, False],
       [False, False, False]])

In [118]:
# Sort one of the arrays you just created in ascending order
sorted_array = np.sort(array_1, axis=None)
sorted_array

array([ 0,  0,  0,  0,  1,  1,  2,  3,  4,  6,  7, 10])

In [119]:
# Sort the indexes of one of the arrays you just created
sorted_indexes = np.argsort(array_1, axis=None)

sorted_indexes

array([ 4,  6,  8, 10,  2, 11,  3,  0,  5,  1,  7,  9], dtype=int64)

In [121]:
# Find the index with the maximum value in one of the arrays you've created
max_value_index = np.unravel_index(np.argmax(array_1, axis=None), array_1.shape)
max_value_index

(3, 0)

In [122]:
# Find the index with the minimum value in one of the arrays you've created
min_value_index = np.unravel_index(np.argmin(array_1, axis=None), array_1.shape)
min_value_index

(1, 1)

In [123]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created

max_value_indices = np.argmax(array_1, axis=1)
max_value_indices

array([1, 2, 1, 0], dtype=int64)

In [124]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
min_value_index = np.argmin(array_1, axis=0)
min_value_index

array([2, 1, 2], dtype=int64)

In [125]:
# Create an array of normally distributed random numbers
normal_array = np.random.normal(loc=0, scale=1, size=(3, 3))
normal_array

array([[ 1.14282281,  0.75193303,  0.79103195],
       [-0.90938745,  1.40279431, -1.40185106],
       [ 0.58685709,  2.19045563, -0.99053633]])

In [126]:
# Create an array with 10 evenly spaced numbers between 1 and 100
evenly_spaced_array = np.linspace(1, 100, 10)
evenly_spaced_array

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.